/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package gestion_de_pharmacie.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import gestion_de_pharmacie.model.Commande;
import gestion_de_pharmacie.model.CommandeModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Commande service. Represents a row in the &quot;Pharma_Commande&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CommandeModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CommandeImpl}.
 * </p>
 *
 * @author Farouk
 * @see CommandeImpl
 * @generated
 */
@JSON(strict = true)
public class CommandeModelImpl
	extends BaseModelImpl<Commande> implements CommandeModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a commande model instance should use the <code>Commande</code> interface instead.
	 */
	public static final String TABLE_NAME = "Pharma_Commande";

	public static final Object[][] TABLE_COLUMNS = {
		{"idCommande", Types.BIGINT}, {"idUtilisateur", Types.BIGINT},
		{"dateCommande", Types.TIMESTAMP}, {"statut", Types.VARCHAR},
		{"montantTotal", Types.DOUBLE}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("idCommande", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("idUtilisateur", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dateCommande", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("statut", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("montantTotal", Types.DOUBLE);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Pharma_Commande (idCommande LONG not null primary key,idUtilisateur LONG,dateCommande DATE null,statut VARCHAR(75) null,montantTotal DOUBLE)";

	public static final String TABLE_SQL_DROP = "drop table Pharma_Commande";

	public static final String ORDER_BY_JPQL =
		" ORDER BY commande.idCommande ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Pharma_Commande.idCommande ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long IDUTILISATEUR_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long IDCOMMANDE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public CommandeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _idCommande;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setIdCommande(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _idCommande;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Commande.class;
	}

	@Override
	public String getModelClassName() {
		return Commande.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Commande, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Commande, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Commande, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Commande)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Commande, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Commande, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Commande)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Commande, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Commande, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Commande, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Commande, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Commande, Object>>();

			attributeGetterFunctions.put("idCommande", Commande::getIdCommande);
			attributeGetterFunctions.put(
				"idUtilisateur", Commande::getIdUtilisateur);
			attributeGetterFunctions.put(
				"dateCommande", Commande::getDateCommande);
			attributeGetterFunctions.put("statut", Commande::getStatut);
			attributeGetterFunctions.put(
				"montantTotal", Commande::getMontantTotal);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Commande, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Commande, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Commande, ?>>();

			attributeSetterBiConsumers.put(
				"idCommande",
				(BiConsumer<Commande, Long>)Commande::setIdCommande);
			attributeSetterBiConsumers.put(
				"idUtilisateur",
				(BiConsumer<Commande, Long>)Commande::setIdUtilisateur);
			attributeSetterBiConsumers.put(
				"dateCommande",
				(BiConsumer<Commande, Date>)Commande::setDateCommande);
			attributeSetterBiConsumers.put(
				"statut", (BiConsumer<Commande, String>)Commande::setStatut);
			attributeSetterBiConsumers.put(
				"montantTotal",
				(BiConsumer<Commande, Double>)Commande::setMontantTotal);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getIdCommande() {
		return _idCommande;
	}

	@Override
	public void setIdCommande(long idCommande) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idCommande = idCommande;
	}

	@JSON
	@Override
	public long getIdUtilisateur() {
		return _idUtilisateur;
	}

	@Override
	public void setIdUtilisateur(long idUtilisateur) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idUtilisateur = idUtilisateur;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalIdUtilisateur() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("idUtilisateur"));
	}

	@JSON
	@Override
	public Date getDateCommande() {
		return _dateCommande;
	}

	@Override
	public void setDateCommande(Date dateCommande) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dateCommande = dateCommande;
	}

	@JSON
	@Override
	public String getStatut() {
		if (_statut == null) {
			return "";
		}
		else {
			return _statut;
		}
	}

	@Override
	public void setStatut(String statut) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statut = statut;
	}

	@JSON
	@Override
	public double getMontantTotal() {
		return _montantTotal;
	}

	@Override
	public void setMontantTotal(double montantTotal) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_montantTotal = montantTotal;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Commande.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Commande toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Commande>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CommandeImpl commandeImpl = new CommandeImpl();

		commandeImpl.setIdCommande(getIdCommande());
		commandeImpl.setIdUtilisateur(getIdUtilisateur());
		commandeImpl.setDateCommande(getDateCommande());
		commandeImpl.setStatut(getStatut());
		commandeImpl.setMontantTotal(getMontantTotal());

		commandeImpl.resetOriginalValues();

		return commandeImpl;
	}

	@Override
	public Commande cloneWithOriginalValues() {
		CommandeImpl commandeImpl = new CommandeImpl();

		commandeImpl.setIdCommande(
			this.<Long>getColumnOriginalValue("idCommande"));
		commandeImpl.setIdUtilisateur(
			this.<Long>getColumnOriginalValue("idUtilisateur"));
		commandeImpl.setDateCommande(
			this.<Date>getColumnOriginalValue("dateCommande"));
		commandeImpl.setStatut(this.<String>getColumnOriginalValue("statut"));
		commandeImpl.setMontantTotal(
			this.<Double>getColumnOriginalValue("montantTotal"));

		return commandeImpl;
	}

	@Override
	public int compareTo(Commande commande) {
		long primaryKey = commande.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Commande)) {
			return false;
		}

		Commande commande = (Commande)object;

		long primaryKey = commande.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Commande> toCacheModel() {
		CommandeCacheModel commandeCacheModel = new CommandeCacheModel();

		commandeCacheModel.idCommande = getIdCommande();

		commandeCacheModel.idUtilisateur = getIdUtilisateur();

		Date dateCommande = getDateCommande();

		if (dateCommande != null) {
			commandeCacheModel.dateCommande = dateCommande.getTime();
		}
		else {
			commandeCacheModel.dateCommande = Long.MIN_VALUE;
		}

		commandeCacheModel.statut = getStatut();

		String statut = commandeCacheModel.statut;

		if ((statut != null) && (statut.length() == 0)) {
			commandeCacheModel.statut = null;
		}

		commandeCacheModel.montantTotal = getMontantTotal();

		return commandeCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Commande, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Commande, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Commande, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Commande)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Commande>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Commande.class, ModelWrapper.class);

	}

	private long _idCommande;
	private long _idUtilisateur;
	private Date _dateCommande;
	private String _statut;
	private double _montantTotal;

	public <T> T getColumnValue(String columnName) {
		Function<Commande, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Commande)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("idCommande", _idCommande);
		_columnOriginalValues.put("idUtilisateur", _idUtilisateur);
		_columnOriginalValues.put("dateCommande", _dateCommande);
		_columnOriginalValues.put("statut", _statut);
		_columnOriginalValues.put("montantTotal", _montantTotal);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("idCommande", 1L);

		columnBitmasks.put("idUtilisateur", 2L);

		columnBitmasks.put("dateCommande", 4L);

		columnBitmasks.put("statut", 8L);

		columnBitmasks.put("montantTotal", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Commande _escapedModel;

}