/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package gestion_de_pharmacie.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import gestion_de_pharmacie.model.CommandeDetail;
import gestion_de_pharmacie.model.CommandeDetailModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CommandeDetail service. Represents a row in the &quot;Pharma_CommandeDetail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CommandeDetailModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CommandeDetailImpl}.
 * </p>
 *
 * @author Farouk
 * @see CommandeDetailImpl
 * @generated
 */
@JSON(strict = true)
public class CommandeDetailModelImpl
	extends BaseModelImpl<CommandeDetail> implements CommandeDetailModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a commande detail model instance should use the <code>CommandeDetail</code> interface instead.
	 */
	public static final String TABLE_NAME = "Pharma_CommandeDetail";

	public static final Object[][] TABLE_COLUMNS = {
		{"idDetail", Types.BIGINT}, {"idCommande", Types.BIGINT},
		{"idMedicament", Types.BIGINT}, {"quantite", Types.INTEGER},
		{"prixUnitaire", Types.DOUBLE}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("idDetail", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("idCommande", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("idMedicament", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("quantite", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("prixUnitaire", Types.DOUBLE);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Pharma_CommandeDetail (idDetail LONG not null primary key,idCommande LONG,idMedicament LONG,quantite INTEGER,prixUnitaire DOUBLE)";

	public static final String TABLE_SQL_DROP =
		"drop table Pharma_CommandeDetail";

	public static final String ORDER_BY_JPQL =
		" ORDER BY commandeDetail.idDetail ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Pharma_CommandeDetail.idDetail ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long IDCOMMANDE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long IDMEDICAMENT_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long IDDETAIL_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public CommandeDetailModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _idDetail;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setIdDetail(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _idDetail;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CommandeDetail.class;
	}

	@Override
	public String getModelClassName() {
		return CommandeDetail.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CommandeDetail, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CommandeDetail, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommandeDetail, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CommandeDetail)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CommandeDetail, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CommandeDetail, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CommandeDetail)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CommandeDetail, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CommandeDetail, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<CommandeDetail, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<CommandeDetail, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<CommandeDetail, Object>>();

			attributeGetterFunctions.put(
				"idDetail", CommandeDetail::getIdDetail);
			attributeGetterFunctions.put(
				"idCommande", CommandeDetail::getIdCommande);
			attributeGetterFunctions.put(
				"idMedicament", CommandeDetail::getIdMedicament);
			attributeGetterFunctions.put(
				"quantite", CommandeDetail::getQuantite);
			attributeGetterFunctions.put(
				"prixUnitaire", CommandeDetail::getPrixUnitaire);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<CommandeDetail, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<CommandeDetail, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<CommandeDetail, ?>>();

			attributeSetterBiConsumers.put(
				"idDetail",
				(BiConsumer<CommandeDetail, Long>)CommandeDetail::setIdDetail);
			attributeSetterBiConsumers.put(
				"idCommande",
				(BiConsumer<CommandeDetail, Long>)
					CommandeDetail::setIdCommande);
			attributeSetterBiConsumers.put(
				"idMedicament",
				(BiConsumer<CommandeDetail, Long>)
					CommandeDetail::setIdMedicament);
			attributeSetterBiConsumers.put(
				"quantite",
				(BiConsumer<CommandeDetail, Integer>)
					CommandeDetail::setQuantite);
			attributeSetterBiConsumers.put(
				"prixUnitaire",
				(BiConsumer<CommandeDetail, Double>)
					CommandeDetail::setPrixUnitaire);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getIdDetail() {
		return _idDetail;
	}

	@Override
	public void setIdDetail(long idDetail) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idDetail = idDetail;
	}

	@JSON
	@Override
	public long getIdCommande() {
		return _idCommande;
	}

	@Override
	public void setIdCommande(long idCommande) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idCommande = idCommande;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalIdCommande() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("idCommande"));
	}

	@JSON
	@Override
	public long getIdMedicament() {
		return _idMedicament;
	}

	@Override
	public void setIdMedicament(long idMedicament) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idMedicament = idMedicament;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalIdMedicament() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("idMedicament"));
	}

	@JSON
	@Override
	public int getQuantite() {
		return _quantite;
	}

	@Override
	public void setQuantite(int quantite) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_quantite = quantite;
	}

	@JSON
	@Override
	public double getPrixUnitaire() {
		return _prixUnitaire;
	}

	@Override
	public void setPrixUnitaire(double prixUnitaire) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_prixUnitaire = prixUnitaire;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, CommandeDetail.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CommandeDetail toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CommandeDetail>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CommandeDetailImpl commandeDetailImpl = new CommandeDetailImpl();

		commandeDetailImpl.setIdDetail(getIdDetail());
		commandeDetailImpl.setIdCommande(getIdCommande());
		commandeDetailImpl.setIdMedicament(getIdMedicament());
		commandeDetailImpl.setQuantite(getQuantite());
		commandeDetailImpl.setPrixUnitaire(getPrixUnitaire());

		commandeDetailImpl.resetOriginalValues();

		return commandeDetailImpl;
	}

	@Override
	public CommandeDetail cloneWithOriginalValues() {
		CommandeDetailImpl commandeDetailImpl = new CommandeDetailImpl();

		commandeDetailImpl.setIdDetail(
			this.<Long>getColumnOriginalValue("idDetail"));
		commandeDetailImpl.setIdCommande(
			this.<Long>getColumnOriginalValue("idCommande"));
		commandeDetailImpl.setIdMedicament(
			this.<Long>getColumnOriginalValue("idMedicament"));
		commandeDetailImpl.setQuantite(
			this.<Integer>getColumnOriginalValue("quantite"));
		commandeDetailImpl.setPrixUnitaire(
			this.<Double>getColumnOriginalValue("prixUnitaire"));

		return commandeDetailImpl;
	}

	@Override
	public int compareTo(CommandeDetail commandeDetail) {
		long primaryKey = commandeDetail.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CommandeDetail)) {
			return false;
		}

		CommandeDetail commandeDetail = (CommandeDetail)object;

		long primaryKey = commandeDetail.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CommandeDetail> toCacheModel() {
		CommandeDetailCacheModel commandeDetailCacheModel =
			new CommandeDetailCacheModel();

		commandeDetailCacheModel.idDetail = getIdDetail();

		commandeDetailCacheModel.idCommande = getIdCommande();

		commandeDetailCacheModel.idMedicament = getIdMedicament();

		commandeDetailCacheModel.quantite = getQuantite();

		commandeDetailCacheModel.prixUnitaire = getPrixUnitaire();

		return commandeDetailCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CommandeDetail, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CommandeDetail, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CommandeDetail, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((CommandeDetail)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CommandeDetail>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					CommandeDetail.class, ModelWrapper.class);

	}

	private long _idDetail;
	private long _idCommande;
	private long _idMedicament;
	private int _quantite;
	private double _prixUnitaire;

	public <T> T getColumnValue(String columnName) {
		Function<CommandeDetail, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((CommandeDetail)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("idDetail", _idDetail);
		_columnOriginalValues.put("idCommande", _idCommande);
		_columnOriginalValues.put("idMedicament", _idMedicament);
		_columnOriginalValues.put("quantite", _quantite);
		_columnOriginalValues.put("prixUnitaire", _prixUnitaire);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("idDetail", 1L);

		columnBitmasks.put("idCommande", 2L);

		columnBitmasks.put("idMedicament", 4L);

		columnBitmasks.put("quantite", 8L);

		columnBitmasks.put("prixUnitaire", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private CommandeDetail _escapedModel;

}