/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package gestion_de_pharmacie.model.impl;

import gestion_de_pharmacie.model.Commande;

import gestion_de_pharmacie.service.CommandeLocalServiceUtil;

/**
 * The extended model base implementation for the Commande service. Represents a row in the &quot;Pharma_Commande&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CommandeImpl}.
 * </p>
 *
 * @author Farouk
 * @see CommandeImpl
 * @see Commande
 * @generated
 */
public abstract class CommandeBaseImpl
	extends CommandeModelImpl implements Commande {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a commande model instance should use the <code>Commande</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CommandeLocalServiceUtil.addCommande(this);
		}
		else {
			CommandeLocalServiceUtil.updateCommande(this);
		}
	}

}