/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package gestion_de_pharmacie.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import gestion_de_pharmacie.model.Fournisseur;
import gestion_de_pharmacie.model.FournisseurModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Fournisseur service. Represents a row in the &quot;Pharma_Fournisseur&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FournisseurModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FournisseurImpl}.
 * </p>
 *
 * @author Farouk
 * @see FournisseurImpl
 * @generated
 */
@JSON(strict = true)
public class FournisseurModelImpl
	extends BaseModelImpl<Fournisseur> implements FournisseurModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a fournisseur model instance should use the <code>Fournisseur</code> interface instead.
	 */
	public static final String TABLE_NAME = "Pharma_Fournisseur";

	public static final Object[][] TABLE_COLUMNS = {
		{"idFournisseur", Types.BIGINT}, {"nom", Types.VARCHAR},
		{"adresse", Types.VARCHAR}, {"telephone", Types.VARCHAR},
		{"email", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("idFournisseur", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("nom", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("adresse", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("telephone", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("email", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Pharma_Fournisseur (idFournisseur LONG not null primary key,nom VARCHAR(75) null,adresse VARCHAR(75) null,telephone VARCHAR(75) null,email VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table Pharma_Fournisseur";

	public static final String ORDER_BY_JPQL =
		" ORDER BY fournisseur.idFournisseur ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Pharma_Fournisseur.idFournisseur ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long IDFOURNISSEUR_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public FournisseurModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _idFournisseur;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setIdFournisseur(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _idFournisseur;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Fournisseur.class;
	}

	@Override
	public String getModelClassName() {
		return Fournisseur.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Fournisseur, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Fournisseur, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Fournisseur, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((Fournisseur)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Fournisseur, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Fournisseur, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Fournisseur)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Fournisseur, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Fournisseur, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Fournisseur, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Fournisseur, Object>>
				attributeGetterFunctions =
					new LinkedHashMap<String, Function<Fournisseur, Object>>();

			attributeGetterFunctions.put(
				"idFournisseur", Fournisseur::getIdFournisseur);
			attributeGetterFunctions.put("nom", Fournisseur::getNom);
			attributeGetterFunctions.put("adresse", Fournisseur::getAdresse);
			attributeGetterFunctions.put(
				"telephone", Fournisseur::getTelephone);
			attributeGetterFunctions.put("email", Fournisseur::getEmail);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Fournisseur, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Fournisseur, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Fournisseur, ?>>();

			attributeSetterBiConsumers.put(
				"idFournisseur",
				(BiConsumer<Fournisseur, Long>)Fournisseur::setIdFournisseur);
			attributeSetterBiConsumers.put(
				"nom", (BiConsumer<Fournisseur, String>)Fournisseur::setNom);
			attributeSetterBiConsumers.put(
				"adresse",
				(BiConsumer<Fournisseur, String>)Fournisseur::setAdresse);
			attributeSetterBiConsumers.put(
				"telephone",
				(BiConsumer<Fournisseur, String>)Fournisseur::setTelephone);
			attributeSetterBiConsumers.put(
				"email",
				(BiConsumer<Fournisseur, String>)Fournisseur::setEmail);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getIdFournisseur() {
		return _idFournisseur;
	}

	@Override
	public void setIdFournisseur(long idFournisseur) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idFournisseur = idFournisseur;
	}

	@JSON
	@Override
	public String getNom() {
		if (_nom == null) {
			return "";
		}
		else {
			return _nom;
		}
	}

	@Override
	public void setNom(String nom) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nom = nom;
	}

	@JSON
	@Override
	public String getAdresse() {
		if (_adresse == null) {
			return "";
		}
		else {
			return _adresse;
		}
	}

	@Override
	public void setAdresse(String adresse) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_adresse = adresse;
	}

	@JSON
	@Override
	public String getTelephone() {
		if (_telephone == null) {
			return "";
		}
		else {
			return _telephone;
		}
	}

	@Override
	public void setTelephone(String telephone) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_telephone = telephone;
	}

	@JSON
	@Override
	public String getEmail() {
		if (_email == null) {
			return "";
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_email = email;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Fournisseur.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Fournisseur toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Fournisseur>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FournisseurImpl fournisseurImpl = new FournisseurImpl();

		fournisseurImpl.setIdFournisseur(getIdFournisseur());
		fournisseurImpl.setNom(getNom());
		fournisseurImpl.setAdresse(getAdresse());
		fournisseurImpl.setTelephone(getTelephone());
		fournisseurImpl.setEmail(getEmail());

		fournisseurImpl.resetOriginalValues();

		return fournisseurImpl;
	}

	@Override
	public Fournisseur cloneWithOriginalValues() {
		FournisseurImpl fournisseurImpl = new FournisseurImpl();

		fournisseurImpl.setIdFournisseur(
			this.<Long>getColumnOriginalValue("idFournisseur"));
		fournisseurImpl.setNom(this.<String>getColumnOriginalValue("nom"));
		fournisseurImpl.setAdresse(
			this.<String>getColumnOriginalValue("adresse"));
		fournisseurImpl.setTelephone(
			this.<String>getColumnOriginalValue("telephone"));
		fournisseurImpl.setEmail(this.<String>getColumnOriginalValue("email"));

		return fournisseurImpl;
	}

	@Override
	public int compareTo(Fournisseur fournisseur) {
		long primaryKey = fournisseur.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Fournisseur)) {
			return false;
		}

		Fournisseur fournisseur = (Fournisseur)object;

		long primaryKey = fournisseur.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Fournisseur> toCacheModel() {
		FournisseurCacheModel fournisseurCacheModel =
			new FournisseurCacheModel();

		fournisseurCacheModel.idFournisseur = getIdFournisseur();

		fournisseurCacheModel.nom = getNom();

		String nom = fournisseurCacheModel.nom;

		if ((nom != null) && (nom.length() == 0)) {
			fournisseurCacheModel.nom = null;
		}

		fournisseurCacheModel.adresse = getAdresse();

		String adresse = fournisseurCacheModel.adresse;

		if ((adresse != null) && (adresse.length() == 0)) {
			fournisseurCacheModel.adresse = null;
		}

		fournisseurCacheModel.telephone = getTelephone();

		String telephone = fournisseurCacheModel.telephone;

		if ((telephone != null) && (telephone.length() == 0)) {
			fournisseurCacheModel.telephone = null;
		}

		fournisseurCacheModel.email = getEmail();

		String email = fournisseurCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			fournisseurCacheModel.email = null;
		}

		return fournisseurCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Fournisseur, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Fournisseur, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Fournisseur, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Fournisseur)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Fournisseur>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Fournisseur.class, ModelWrapper.class);

	}

	private long _idFournisseur;
	private String _nom;
	private String _adresse;
	private String _telephone;
	private String _email;

	public <T> T getColumnValue(String columnName) {
		Function<Fournisseur, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Fournisseur)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("idFournisseur", _idFournisseur);
		_columnOriginalValues.put("nom", _nom);
		_columnOriginalValues.put("adresse", _adresse);
		_columnOriginalValues.put("telephone", _telephone);
		_columnOriginalValues.put("email", _email);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("idFournisseur", 1L);

		columnBitmasks.put("nom", 2L);

		columnBitmasks.put("adresse", 4L);

		columnBitmasks.put("telephone", 8L);

		columnBitmasks.put("email", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Fournisseur _escapedModel;

}