/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package gestion_de_pharmacie.model.impl;

import gestion_de_pharmacie.model.Fournisseur;

import gestion_de_pharmacie.service.FournisseurLocalServiceUtil;

/**
 * The extended model base implementation for the Fournisseur service. Represents a row in the &quot;Pharma_Fournisseur&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FournisseurImpl}.
 * </p>
 *
 * @author Farouk
 * @see FournisseurImpl
 * @see Fournisseur
 * @generated
 */
public abstract class FournisseurBaseImpl
	extends FournisseurModelImpl implements Fournisseur {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a fournisseur model instance should use the <code>Fournisseur</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			FournisseurLocalServiceUtil.addFournisseur(this);
		}
		else {
			FournisseurLocalServiceUtil.updateFournisseur(this);
		}
	}

}