/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package gestion_de_pharmacie.model.impl;

import gestion_de_pharmacie.model.MouvementStock;

import gestion_de_pharmacie.service.MouvementStockLocalServiceUtil;

/**
 * The extended model base implementation for the MouvementStock service. Represents a row in the &quot;Pharma_MouvementStock&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MouvementStockImpl}.
 * </p>
 *
 * @author Farouk
 * @see MouvementStockImpl
 * @see MouvementStock
 * @generated
 */
public abstract class MouvementStockBaseImpl
	extends MouvementStockModelImpl implements MouvementStock {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a mouvement stock model instance should use the <code>MouvementStock</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			MouvementStockLocalServiceUtil.addMouvementStock(this);
		}
		else {
			MouvementStockLocalServiceUtil.updateMouvementStock(this);
		}
	}

}