/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package gestion_de_pharmacie.model.impl;

import gestion_de_pharmacie.model.Stock;

import gestion_de_pharmacie.service.StockLocalServiceUtil;

/**
 * The extended model base implementation for the Stock service. Represents a row in the &quot;Pharma_Stock&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StockImpl}.
 * </p>
 *
 * @author Farouk
 * @see StockImpl
 * @see Stock
 * @generated
 */
public abstract class StockBaseImpl extends StockModelImpl implements Stock {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a stock model instance should use the <code>Stock</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			StockLocalServiceUtil.addStock(this);
		}
		else {
			StockLocalServiceUtil.updateStock(this);
		}
	}

}