/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package gestion_de_pharmacie.model.impl;

import gestion_de_pharmacie.model.Utilisateur;

import gestion_de_pharmacie.service.UtilisateurLocalServiceUtil;

/**
 * The extended model base implementation for the Utilisateur service. Represents a row in the &quot;Pharma_Utilisateur&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UtilisateurImpl}.
 * </p>
 *
 * @author Farouk
 * @see UtilisateurImpl
 * @see Utilisateur
 * @generated
 */
public abstract class UtilisateurBaseImpl
	extends UtilisateurModelImpl implements Utilisateur {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a utilisateur model instance should use the <code>Utilisateur</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			UtilisateurLocalServiceUtil.addUtilisateur(this);
		}
		else {
			UtilisateurLocalServiceUtil.updateUtilisateur(this);
		}
	}

}