/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package gestion_de_pharmacie.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import gestion_de_pharmacie.model.Vente;
import gestion_de_pharmacie.model.VenteModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Vente service. Represents a row in the &quot;Pharma_Vente&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>VenteModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VenteImpl}.
 * </p>
 *
 * @author Farouk
 * @see VenteImpl
 * @generated
 */
@JSON(strict = true)
public class VenteModelImpl extends BaseModelImpl<Vente> implements VenteModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a vente model instance should use the <code>Vente</code> interface instead.
	 */
	public static final String TABLE_NAME = "Pharma_Vente";

	public static final Object[][] TABLE_COLUMNS = {
		{"idVente", Types.BIGINT}, {"idUtilisateur", Types.BIGINT},
		{"dateVente", Types.TIMESTAMP}, {"montantTotal", Types.DOUBLE}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("idVente", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("idUtilisateur", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dateVente", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("montantTotal", Types.DOUBLE);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Pharma_Vente (idVente LONG not null primary key,idUtilisateur LONG,dateVente DATE null,montantTotal DOUBLE)";

	public static final String TABLE_SQL_DROP = "drop table Pharma_Vente";

	public static final String ORDER_BY_JPQL = " ORDER BY vente.idVente ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Pharma_Vente.idVente ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long IDVENTE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public VenteModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _idVente;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setIdVente(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _idVente;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Vente.class;
	}

	@Override
	public String getModelClassName() {
		return Vente.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Vente, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Vente, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Vente, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Vente)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Vente, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Vente, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Vente)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Vente, Object>> getAttributeGetterFunctions() {
		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Vente, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Vente, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Vente, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Vente, Object>>();

			attributeGetterFunctions.put("idVente", Vente::getIdVente);
			attributeGetterFunctions.put(
				"idUtilisateur", Vente::getIdUtilisateur);
			attributeGetterFunctions.put("dateVente", Vente::getDateVente);
			attributeGetterFunctions.put(
				"montantTotal", Vente::getMontantTotal);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Vente, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Vente, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Vente, ?>>();

			attributeSetterBiConsumers.put(
				"idVente", (BiConsumer<Vente, Long>)Vente::setIdVente);
			attributeSetterBiConsumers.put(
				"idUtilisateur",
				(BiConsumer<Vente, Long>)Vente::setIdUtilisateur);
			attributeSetterBiConsumers.put(
				"dateVente", (BiConsumer<Vente, Date>)Vente::setDateVente);
			attributeSetterBiConsumers.put(
				"montantTotal",
				(BiConsumer<Vente, Double>)Vente::setMontantTotal);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getIdVente() {
		return _idVente;
	}

	@Override
	public void setIdVente(long idVente) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idVente = idVente;
	}

	@JSON
	@Override
	public long getIdUtilisateur() {
		return _idUtilisateur;
	}

	@Override
	public void setIdUtilisateur(long idUtilisateur) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idUtilisateur = idUtilisateur;
	}

	@JSON
	@Override
	public Date getDateVente() {
		return _dateVente;
	}

	@Override
	public void setDateVente(Date dateVente) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dateVente = dateVente;
	}

	@JSON
	@Override
	public double getMontantTotal() {
		return _montantTotal;
	}

	@Override
	public void setMontantTotal(double montantTotal) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_montantTotal = montantTotal;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Vente.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Vente toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Vente>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VenteImpl venteImpl = new VenteImpl();

		venteImpl.setIdVente(getIdVente());
		venteImpl.setIdUtilisateur(getIdUtilisateur());
		venteImpl.setDateVente(getDateVente());
		venteImpl.setMontantTotal(getMontantTotal());

		venteImpl.resetOriginalValues();

		return venteImpl;
	}

	@Override
	public Vente cloneWithOriginalValues() {
		VenteImpl venteImpl = new VenteImpl();

		venteImpl.setIdVente(this.<Long>getColumnOriginalValue("idVente"));
		venteImpl.setIdUtilisateur(
			this.<Long>getColumnOriginalValue("idUtilisateur"));
		venteImpl.setDateVente(this.<Date>getColumnOriginalValue("dateVente"));
		venteImpl.setMontantTotal(
			this.<Double>getColumnOriginalValue("montantTotal"));

		return venteImpl;
	}

	@Override
	public int compareTo(Vente vente) {
		long primaryKey = vente.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Vente)) {
			return false;
		}

		Vente vente = (Vente)object;

		long primaryKey = vente.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Vente> toCacheModel() {
		VenteCacheModel venteCacheModel = new VenteCacheModel();

		venteCacheModel.idVente = getIdVente();

		venteCacheModel.idUtilisateur = getIdUtilisateur();

		Date dateVente = getDateVente();

		if (dateVente != null) {
			venteCacheModel.dateVente = dateVente.getTime();
		}
		else {
			venteCacheModel.dateVente = Long.MIN_VALUE;
		}

		venteCacheModel.montantTotal = getMontantTotal();

		return venteCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Vente, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Vente, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Vente, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Vente)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Vente>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Vente.class, ModelWrapper.class);

	}

	private long _idVente;
	private long _idUtilisateur;
	private Date _dateVente;
	private double _montantTotal;

	public <T> T getColumnValue(String columnName) {
		Function<Vente, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Vente)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("idVente", _idVente);
		_columnOriginalValues.put("idUtilisateur", _idUtilisateur);
		_columnOriginalValues.put("dateVente", _dateVente);
		_columnOriginalValues.put("montantTotal", _montantTotal);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("idVente", 1L);

		columnBitmasks.put("idUtilisateur", 2L);

		columnBitmasks.put("dateVente", 4L);

		columnBitmasks.put("montantTotal", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Vente _escapedModel;

}