/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package gestion_de_pharmacie.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import gestion_de_pharmacie.model.VenteDetail;
import gestion_de_pharmacie.model.VenteDetailModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the VenteDetail service. Represents a row in the &quot;Pharma_VenteDetail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>VenteDetailModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VenteDetailImpl}.
 * </p>
 *
 * @author Farouk
 * @see VenteDetailImpl
 * @generated
 */
@JSON(strict = true)
public class VenteDetailModelImpl
	extends BaseModelImpl<VenteDetail> implements VenteDetailModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a vente detail model instance should use the <code>VenteDetail</code> interface instead.
	 */
	public static final String TABLE_NAME = "Pharma_VenteDetail";

	public static final Object[][] TABLE_COLUMNS = {
		{"idDetail", Types.BIGINT}, {"idVente", Types.BIGINT},
		{"idMedicament", Types.BIGINT}, {"quantite", Types.INTEGER},
		{"prixUnitaire", Types.DOUBLE}, {"sousTotal", Types.DOUBLE}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("idDetail", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("idVente", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("idMedicament", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("quantite", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("prixUnitaire", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("sousTotal", Types.DOUBLE);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Pharma_VenteDetail (idDetail LONG not null primary key,idVente LONG,idMedicament LONG,quantite INTEGER,prixUnitaire DOUBLE,sousTotal DOUBLE)";

	public static final String TABLE_SQL_DROP = "drop table Pharma_VenteDetail";

	public static final String ORDER_BY_JPQL =
		" ORDER BY venteDetail.idDetail ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Pharma_VenteDetail.idDetail ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long IDDETAIL_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public VenteDetailModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _idDetail;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setIdDetail(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _idDetail;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return VenteDetail.class;
	}

	@Override
	public String getModelClassName() {
		return VenteDetail.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<VenteDetail, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<VenteDetail, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<VenteDetail, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((VenteDetail)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<VenteDetail, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<VenteDetail, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(VenteDetail)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<VenteDetail, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<VenteDetail, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<VenteDetail, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<VenteDetail, Object>>
				attributeGetterFunctions =
					new LinkedHashMap<String, Function<VenteDetail, Object>>();

			attributeGetterFunctions.put("idDetail", VenteDetail::getIdDetail);
			attributeGetterFunctions.put("idVente", VenteDetail::getIdVente);
			attributeGetterFunctions.put(
				"idMedicament", VenteDetail::getIdMedicament);
			attributeGetterFunctions.put("quantite", VenteDetail::getQuantite);
			attributeGetterFunctions.put(
				"prixUnitaire", VenteDetail::getPrixUnitaire);
			attributeGetterFunctions.put(
				"sousTotal", VenteDetail::getSousTotal);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<VenteDetail, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<VenteDetail, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<VenteDetail, ?>>();

			attributeSetterBiConsumers.put(
				"idDetail",
				(BiConsumer<VenteDetail, Long>)VenteDetail::setIdDetail);
			attributeSetterBiConsumers.put(
				"idVente",
				(BiConsumer<VenteDetail, Long>)VenteDetail::setIdVente);
			attributeSetterBiConsumers.put(
				"idMedicament",
				(BiConsumer<VenteDetail, Long>)VenteDetail::setIdMedicament);
			attributeSetterBiConsumers.put(
				"quantite",
				(BiConsumer<VenteDetail, Integer>)VenteDetail::setQuantite);
			attributeSetterBiConsumers.put(
				"prixUnitaire",
				(BiConsumer<VenteDetail, Double>)VenteDetail::setPrixUnitaire);
			attributeSetterBiConsumers.put(
				"sousTotal",
				(BiConsumer<VenteDetail, Double>)VenteDetail::setSousTotal);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getIdDetail() {
		return _idDetail;
	}

	@Override
	public void setIdDetail(long idDetail) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idDetail = idDetail;
	}

	@JSON
	@Override
	public long getIdVente() {
		return _idVente;
	}

	@Override
	public void setIdVente(long idVente) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idVente = idVente;
	}

	@JSON
	@Override
	public long getIdMedicament() {
		return _idMedicament;
	}

	@Override
	public void setIdMedicament(long idMedicament) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idMedicament = idMedicament;
	}

	@JSON
	@Override
	public int getQuantite() {
		return _quantite;
	}

	@Override
	public void setQuantite(int quantite) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_quantite = quantite;
	}

	@JSON
	@Override
	public double getPrixUnitaire() {
		return _prixUnitaire;
	}

	@Override
	public void setPrixUnitaire(double prixUnitaire) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_prixUnitaire = prixUnitaire;
	}

	@JSON
	@Override
	public double getSousTotal() {
		return _sousTotal;
	}

	@Override
	public void setSousTotal(double sousTotal) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sousTotal = sousTotal;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, VenteDetail.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public VenteDetail toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, VenteDetail>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VenteDetailImpl venteDetailImpl = new VenteDetailImpl();

		venteDetailImpl.setIdDetail(getIdDetail());
		venteDetailImpl.setIdVente(getIdVente());
		venteDetailImpl.setIdMedicament(getIdMedicament());
		venteDetailImpl.setQuantite(getQuantite());
		venteDetailImpl.setPrixUnitaire(getPrixUnitaire());
		venteDetailImpl.setSousTotal(getSousTotal());

		venteDetailImpl.resetOriginalValues();

		return venteDetailImpl;
	}

	@Override
	public VenteDetail cloneWithOriginalValues() {
		VenteDetailImpl venteDetailImpl = new VenteDetailImpl();

		venteDetailImpl.setIdDetail(
			this.<Long>getColumnOriginalValue("idDetail"));
		venteDetailImpl.setIdVente(
			this.<Long>getColumnOriginalValue("idVente"));
		venteDetailImpl.setIdMedicament(
			this.<Long>getColumnOriginalValue("idMedicament"));
		venteDetailImpl.setQuantite(
			this.<Integer>getColumnOriginalValue("quantite"));
		venteDetailImpl.setPrixUnitaire(
			this.<Double>getColumnOriginalValue("prixUnitaire"));
		venteDetailImpl.setSousTotal(
			this.<Double>getColumnOriginalValue("sousTotal"));

		return venteDetailImpl;
	}

	@Override
	public int compareTo(VenteDetail venteDetail) {
		long primaryKey = venteDetail.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof VenteDetail)) {
			return false;
		}

		VenteDetail venteDetail = (VenteDetail)object;

		long primaryKey = venteDetail.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<VenteDetail> toCacheModel() {
		VenteDetailCacheModel venteDetailCacheModel =
			new VenteDetailCacheModel();

		venteDetailCacheModel.idDetail = getIdDetail();

		venteDetailCacheModel.idVente = getIdVente();

		venteDetailCacheModel.idMedicament = getIdMedicament();

		venteDetailCacheModel.quantite = getQuantite();

		venteDetailCacheModel.prixUnitaire = getPrixUnitaire();

		venteDetailCacheModel.sousTotal = getSousTotal();

		return venteDetailCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<VenteDetail, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<VenteDetail, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<VenteDetail, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((VenteDetail)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, VenteDetail>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					VenteDetail.class, ModelWrapper.class);

	}

	private long _idDetail;
	private long _idVente;
	private long _idMedicament;
	private int _quantite;
	private double _prixUnitaire;
	private double _sousTotal;

	public <T> T getColumnValue(String columnName) {
		Function<VenteDetail, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((VenteDetail)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("idDetail", _idDetail);
		_columnOriginalValues.put("idVente", _idVente);
		_columnOriginalValues.put("idMedicament", _idMedicament);
		_columnOriginalValues.put("quantite", _quantite);
		_columnOriginalValues.put("prixUnitaire", _prixUnitaire);
		_columnOriginalValues.put("sousTotal", _sousTotal);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("idDetail", 1L);

		columnBitmasks.put("idVente", 2L);

		columnBitmasks.put("idMedicament", 4L);

		columnBitmasks.put("quantite", 8L);

		columnBitmasks.put("prixUnitaire", 16L);

		columnBitmasks.put("sousTotal", 32L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private VenteDetail _escapedModel;

}