/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package gestion_de_pharmacie.model.impl;

import gestion_de_pharmacie.model.VenteDetail;

import gestion_de_pharmacie.service.VenteDetailLocalServiceUtil;

/**
 * The extended model base implementation for the VenteDetail service. Represents a row in the &quot;Pharma_VenteDetail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VenteDetailImpl}.
 * </p>
 *
 * @author Farouk
 * @see VenteDetailImpl
 * @see VenteDetail
 * @generated
 */
public abstract class VenteDetailBaseImpl
	extends VenteDetailModelImpl implements VenteDetail {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a vente detail model instance should use the <code>VenteDetail</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			VenteDetailLocalServiceUtil.addVenteDetail(this);
		}
		else {
			VenteDetailLocalServiceUtil.updateVenteDetail(this);
		}
	}

}