<%@ page contentType="text/html; charset=UTF-8" %>
<%@ page import="java.util.*" %>
<%@ page import="java.text.*" %>
<%@ page import="gestion_de_pharmacie.model.*" %>
<%@ page import="gestion_de_pharmacie.service.*" %>
<%@ taglib uri="http://java.sun.com/portlet_2_0" prefix="portlet" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>

<portlet:defineObjects />

<%
    long commandeId = 0L;
    try { commandeId = Long.parseLong(request.getParameter("commandeId")); } catch(Exception ignore){}

    Commande cmd = CommandeLocalServiceUtil.fetchCommande(commandeId);
    if (cmd == null) {
%>
<div class="card">Commande introuvable.</div>
<%
        return;
    }

    Utilisateur fournisseur = UtilisateurLocalServiceUtil.fetchUtilisateur(cmd.getIdUtilisateur());
    String fournisseurName = (fournisseur != null) ? (fournisseur.getNom() + " " + fournisseur.getPrenom()) : "-";

    // Finder generated by <finder name="IdCommande" ... />
    List<CommandeDetail> details;
    try {
        details = CommandeDetailLocalServiceUtil.findByCommandeId(commandeId);
    } catch (Throwable t) {
        // Some service-builder versions expose (id,start,end)
        details = CommandeDetailLocalServiceUtil.findByCommandeId(commandeId, -1, -1);
    }

    NumberFormat money = NumberFormat.getNumberInstance(Locale.FRANCE);
    money.setMinimumFractionDigits(2); money.setMaximumFractionDigits(2);
%>

<style>
    .wrap{max-width:1000px;margin:24px auto;padding:0 16px;font-family:Segoe UI,Tahoma,Arial}
    .card{background:#fff;border:1px solid #E5E7EB;border-radius:12px;padding:16px;margin-bottom:16px}
    h2{margin:0 0 12px}
    table{width:100%;border-collapse:collapse}
    th,td{padding:10px;border-bottom:1px solid #E5E7EB;text-align:left}
    thead th{background:#F8FAFC}
    .muted{color:#6B7280}
    .row{display:flex;gap:16px;flex-wrap:wrap}
    .col{flex:1 1 300px}
    .btn{display:inline-block;padding:8px 12px;border-radius:8px;background:#1E3A8A;color:#fff;text-decoration:none}
</style>

<div class="wrap">
    <div class="card">
        <h2>Bon de commande #<%= cmd.getIdCommande() %></h2>
        <div class="row">
            <div class="col">
                <div class="muted">Fournisseur</div>
                <div><%= fournisseurName %></div>
            </div>
            <div class="col">
                <div class="muted">Date</div>
                <div><fmt:formatDate value="<%= cmd.getDateCommande() %>" pattern="dd/MM/yyyy HH:mm" /></div>
            </div>
            <div class="col">
                <div class="muted">Statut</div>
                <div><%= cmd.getStatut() %></div>
            </div>
            <div class="col">
                <div class="muted">Montant total</div>
                <div><%= money.format(cmd.getMontantTotal()) %> DH</div>
            </div>
        </div>
    </div>

    <div class="card">
        <table>
            <thead>
            <tr>
                <th>#</th>
                <th>Médicament</th>
                <th>Prix unitaire</th>
                <th>Quantité</th>
                <th>Sous-total</th>
            </tr>
            </thead>
            <tbody>
            <%
                int i=1;
                for (CommandeDetail d : details) {
                    Medicament m = MedicamentLocalServiceUtil.fetchMedicament(d.getIdMedicament());
                    String medName = (m!=null)? m.getNom() : ("ID="+d.getIdMedicament());
                    double subtotal = d.getPrixUnitaire() * d.getQuantite();
            %>
            <tr>
                <td><%= i++ %></td>
                <td><%= medName %></td>
                <td><%= money.format(d.getPrixUnitaire()) %> DH</td>
                <td><%= d.getQuantite() %></td>
                <td><%= money.format(subtotal) %> DH</td>
            </tr>
            <% } %>
            </tbody>
        </table>
    </div>

    <div class="card" style="display:flex;gap:10px;">
        <portlet:renderURL var="backUrl">
            <portlet:param name="mvcPath" value="/view.jsp"/>
        </portlet:renderURL>

        <a class="btn" href="${backUrl}">← Retour</a>

        <portlet:resourceURL id="downloadCommandePdf" var="pdfURL">
            <portlet:param name="commandeId" value="<%= String.valueOf(cmd.getIdCommande()) %>" />
        </portlet:resourceURL>

        <a class="btn" href="${pdfURL}">Télécharger PDF</a>

    </div>
</div>
