/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package gestion_de_pharmacie.model;

import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CommandeDetail service. Represents a row in the &quot;Pharma_CommandeDetail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>gestion_de_pharmacie.model.impl.CommandeDetailModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>gestion_de_pharmacie.model.impl.CommandeDetailImpl</code>.
 * </p>
 *
 * @author Farouk
 * @see CommandeDetail
 * @generated
 */
@ProviderType
public interface CommandeDetailModel extends BaseModel<CommandeDetail> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a commande detail model instance should use the {@link CommandeDetail} interface instead.
	 */

	/**
	 * Returns the primary key of this commande detail.
	 *
	 * @return the primary key of this commande detail
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this commande detail.
	 *
	 * @param primaryKey the primary key of this commande detail
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id detail of this commande detail.
	 *
	 * @return the id detail of this commande detail
	 */
	public long getIdDetail();

	/**
	 * Sets the id detail of this commande detail.
	 *
	 * @param idDetail the id detail of this commande detail
	 */
	public void setIdDetail(long idDetail);

	/**
	 * Returns the id commande of this commande detail.
	 *
	 * @return the id commande of this commande detail
	 */
	public long getIdCommande();

	/**
	 * Sets the id commande of this commande detail.
	 *
	 * @param idCommande the id commande of this commande detail
	 */
	public void setIdCommande(long idCommande);

	/**
	 * Returns the id medicament of this commande detail.
	 *
	 * @return the id medicament of this commande detail
	 */
	public long getIdMedicament();

	/**
	 * Sets the id medicament of this commande detail.
	 *
	 * @param idMedicament the id medicament of this commande detail
	 */
	public void setIdMedicament(long idMedicament);

	/**
	 * Returns the quantite of this commande detail.
	 *
	 * @return the quantite of this commande detail
	 */
	public int getQuantite();

	/**
	 * Sets the quantite of this commande detail.
	 *
	 * @param quantite the quantite of this commande detail
	 */
	public void setQuantite(int quantite);

	/**
	 * Returns the prix unitaire of this commande detail.
	 *
	 * @return the prix unitaire of this commande detail
	 */
	public double getPrixUnitaire();

	/**
	 * Sets the prix unitaire of this commande detail.
	 *
	 * @param prixUnitaire the prix unitaire of this commande detail
	 */
	public void setPrixUnitaire(double prixUnitaire);

	@Override
	public CommandeDetail cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}