/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package gestion_de_pharmacie.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Commande service. Represents a row in the &quot;Pharma_Commande&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>gestion_de_pharmacie.model.impl.CommandeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>gestion_de_pharmacie.model.impl.CommandeImpl</code>.
 * </p>
 *
 * @author Farouk
 * @see Commande
 * @generated
 */
@ProviderType
public interface CommandeModel extends BaseModel<Commande> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a commande model instance should use the {@link Commande} interface instead.
	 */

	/**
	 * Returns the primary key of this commande.
	 *
	 * @return the primary key of this commande
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this commande.
	 *
	 * @param primaryKey the primary key of this commande
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id commande of this commande.
	 *
	 * @return the id commande of this commande
	 */
	public long getIdCommande();

	/**
	 * Sets the id commande of this commande.
	 *
	 * @param idCommande the id commande of this commande
	 */
	public void setIdCommande(long idCommande);

	/**
	 * Returns the id fournisseur of this commande.
	 *
	 * @return the id fournisseur of this commande
	 */
	public long getIdFournisseur();

	/**
	 * Sets the id fournisseur of this commande.
	 *
	 * @param idFournisseur the id fournisseur of this commande
	 */
	public void setIdFournisseur(long idFournisseur);

	/**
	 * Returns the date commande of this commande.
	 *
	 * @return the date commande of this commande
	 */
	public Date getDateCommande();

	/**
	 * Sets the date commande of this commande.
	 *
	 * @param dateCommande the date commande of this commande
	 */
	public void setDateCommande(Date dateCommande);

	/**
	 * Returns the statut of this commande.
	 *
	 * @return the statut of this commande
	 */
	@AutoEscape
	public String getStatut();

	/**
	 * Sets the statut of this commande.
	 *
	 * @param statut the statut of this commande
	 */
	public void setStatut(String statut);

	/**
	 * Returns the montant total of this commande.
	 *
	 * @return the montant total of this commande
	 */
	public double getMontantTotal();

	/**
	 * Sets the montant total of this commande.
	 *
	 * @param montantTotal the montant total of this commande
	 */
	public void setMontantTotal(double montantTotal);

	@Override
	public Commande cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}