/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package gestion_de_pharmacie.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Fournisseur service. Represents a row in the &quot;Pharma_Fournisseur&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>gestion_de_pharmacie.model.impl.FournisseurModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>gestion_de_pharmacie.model.impl.FournisseurImpl</code>.
 * </p>
 *
 * @author Farouk
 * @see Fournisseur
 * @generated
 */
@ProviderType
public interface FournisseurModel extends BaseModel<Fournisseur> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a fournisseur model instance should use the {@link Fournisseur} interface instead.
	 */

	/**
	 * Returns the primary key of this fournisseur.
	 *
	 * @return the primary key of this fournisseur
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this fournisseur.
	 *
	 * @param primaryKey the primary key of this fournisseur
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id fournisseur of this fournisseur.
	 *
	 * @return the id fournisseur of this fournisseur
	 */
	public long getIdFournisseur();

	/**
	 * Sets the id fournisseur of this fournisseur.
	 *
	 * @param idFournisseur the id fournisseur of this fournisseur
	 */
	public void setIdFournisseur(long idFournisseur);

	/**
	 * Returns the nom of this fournisseur.
	 *
	 * @return the nom of this fournisseur
	 */
	@AutoEscape
	public String getNom();

	/**
	 * Sets the nom of this fournisseur.
	 *
	 * @param nom the nom of this fournisseur
	 */
	public void setNom(String nom);

	/**
	 * Returns the adresse of this fournisseur.
	 *
	 * @return the adresse of this fournisseur
	 */
	@AutoEscape
	public String getAdresse();

	/**
	 * Sets the adresse of this fournisseur.
	 *
	 * @param adresse the adresse of this fournisseur
	 */
	public void setAdresse(String adresse);

	/**
	 * Returns the telephone of this fournisseur.
	 *
	 * @return the telephone of this fournisseur
	 */
	@AutoEscape
	public String getTelephone();

	/**
	 * Sets the telephone of this fournisseur.
	 *
	 * @param telephone the telephone of this fournisseur
	 */
	public void setTelephone(String telephone);

	/**
	 * Returns the email of this fournisseur.
	 *
	 * @return the email of this fournisseur
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this fournisseur.
	 *
	 * @param email the email of this fournisseur
	 */
	public void setEmail(String email);

	@Override
	public Fournisseur cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}