/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package gestion_de_pharmacie.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Medicament service. Represents a row in the &quot;Pharma_Medicament&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>gestion_de_pharmacie.model.impl.MedicamentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>gestion_de_pharmacie.model.impl.MedicamentImpl</code>.
 * </p>
 *
 * @author Farouk
 * @see Medicament
 * @generated
 */
@ProviderType
public interface MedicamentModel extends BaseModel<Medicament> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a medicament model instance should use the {@link Medicament} interface instead.
	 */

	/**
	 * Returns the primary key of this medicament.
	 *
	 * @return the primary key of this medicament
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this medicament.
	 *
	 * @param primaryKey the primary key of this medicament
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id medicament of this medicament.
	 *
	 * @return the id medicament of this medicament
	 */
	public long getIdMedicament();

	/**
	 * Sets the id medicament of this medicament.
	 *
	 * @param idMedicament the id medicament of this medicament
	 */
	public void setIdMedicament(long idMedicament);

	/**
	 * Returns the code of this medicament.
	 *
	 * @return the code of this medicament
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this medicament.
	 *
	 * @param code the code of this medicament
	 */
	public void setCode(String code);

	/**
	 * Returns the code barre of this medicament.
	 *
	 * @return the code barre of this medicament
	 */
	@AutoEscape
	public String getCodeBarre();

	/**
	 * Sets the code barre of this medicament.
	 *
	 * @param codeBarre the code barre of this medicament
	 */
	public void setCodeBarre(String codeBarre);

	/**
	 * Returns the nom of this medicament.
	 *
	 * @return the nom of this medicament
	 */
	@AutoEscape
	public String getNom();

	/**
	 * Sets the nom of this medicament.
	 *
	 * @param nom the nom of this medicament
	 */
	public void setNom(String nom);

	/**
	 * Returns the description of this medicament.
	 *
	 * @return the description of this medicament
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this medicament.
	 *
	 * @param description the description of this medicament
	 */
	public void setDescription(String description);

	/**
	 * Returns the categorie of this medicament.
	 *
	 * @return the categorie of this medicament
	 */
	@AutoEscape
	public String getCategorie();

	/**
	 * Sets the categorie of this medicament.
	 *
	 * @param categorie the categorie of this medicament
	 */
	public void setCategorie(String categorie);

	/**
	 * Returns the prix unitaire of this medicament.
	 *
	 * @return the prix unitaire of this medicament
	 */
	public double getPrixUnitaire();

	/**
	 * Sets the prix unitaire of this medicament.
	 *
	 * @param prixUnitaire the prix unitaire of this medicament
	 */
	public void setPrixUnitaire(double prixUnitaire);

	/**
	 * Returns the seuil minimum of this medicament.
	 *
	 * @return the seuil minimum of this medicament
	 */
	public int getSeuilMinimum();

	/**
	 * Sets the seuil minimum of this medicament.
	 *
	 * @param seuilMinimum the seuil minimum of this medicament
	 */
	public void setSeuilMinimum(int seuilMinimum);

	/**
	 * Returns the date ajout of this medicament.
	 *
	 * @return the date ajout of this medicament
	 */
	public Date getDateAjout();

	/**
	 * Sets the date ajout of this medicament.
	 *
	 * @param dateAjout the date ajout of this medicament
	 */
	public void setDateAjout(Date dateAjout);

	@Override
	public Medicament cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}