/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package gestion_de_pharmacie.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the MouvementStock service. Represents a row in the &quot;Pharma_MouvementStock&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>gestion_de_pharmacie.model.impl.MouvementStockModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>gestion_de_pharmacie.model.impl.MouvementStockImpl</code>.
 * </p>
 *
 * @author Farouk
 * @see MouvementStock
 * @generated
 */
@ProviderType
public interface MouvementStockModel extends BaseModel<MouvementStock> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a mouvement stock model instance should use the {@link MouvementStock} interface instead.
	 */

	/**
	 * Returns the primary key of this mouvement stock.
	 *
	 * @return the primary key of this mouvement stock
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this mouvement stock.
	 *
	 * @param primaryKey the primary key of this mouvement stock
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id mouvement of this mouvement stock.
	 *
	 * @return the id mouvement of this mouvement stock
	 */
	public long getIdMouvement();

	/**
	 * Sets the id mouvement of this mouvement stock.
	 *
	 * @param idMouvement the id mouvement of this mouvement stock
	 */
	public void setIdMouvement(long idMouvement);

	/**
	 * Returns the id stock of this mouvement stock.
	 *
	 * @return the id stock of this mouvement stock
	 */
	public long getIdStock();

	/**
	 * Sets the id stock of this mouvement stock.
	 *
	 * @param idStock the id stock of this mouvement stock
	 */
	public void setIdStock(long idStock);

	/**
	 * Returns the type mouvement of this mouvement stock.
	 *
	 * @return the type mouvement of this mouvement stock
	 */
	@AutoEscape
	public String getTypeMouvement();

	/**
	 * Sets the type mouvement of this mouvement stock.
	 *
	 * @param typeMouvement the type mouvement of this mouvement stock
	 */
	public void setTypeMouvement(String typeMouvement);

	/**
	 * Returns the quantite of this mouvement stock.
	 *
	 * @return the quantite of this mouvement stock
	 */
	public int getQuantite();

	/**
	 * Sets the quantite of this mouvement stock.
	 *
	 * @param quantite the quantite of this mouvement stock
	 */
	public void setQuantite(int quantite);

	/**
	 * Returns the date mouvement of this mouvement stock.
	 *
	 * @return the date mouvement of this mouvement stock
	 */
	public Date getDateMouvement();

	/**
	 * Sets the date mouvement of this mouvement stock.
	 *
	 * @param dateMouvement the date mouvement of this mouvement stock
	 */
	public void setDateMouvement(Date dateMouvement);

	@Override
	public MouvementStock cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}