/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package gestion_de_pharmacie.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Notification service. Represents a row in the &quot;Pharma_Notification&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>gestion_de_pharmacie.model.impl.NotificationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>gestion_de_pharmacie.model.impl.NotificationImpl</code>.
 * </p>
 *
 * @author Farouk
 * @see Notification
 * @generated
 */
@ProviderType
public interface NotificationModel extends BaseModel<Notification> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a notification model instance should use the {@link Notification} interface instead.
	 */

	/**
	 * Returns the primary key of this notification.
	 *
	 * @return the primary key of this notification
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this notification.
	 *
	 * @param primaryKey the primary key of this notification
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id notification of this notification.
	 *
	 * @return the id notification of this notification
	 */
	public long getIdNotification();

	/**
	 * Sets the id notification of this notification.
	 *
	 * @param idNotification the id notification of this notification
	 */
	public void setIdNotification(long idNotification);

	/**
	 * Returns the id utilisateur of this notification.
	 *
	 * @return the id utilisateur of this notification
	 */
	public long getIdUtilisateur();

	/**
	 * Sets the id utilisateur of this notification.
	 *
	 * @param idUtilisateur the id utilisateur of this notification
	 */
	public void setIdUtilisateur(long idUtilisateur);

	/**
	 * Returns the type of this notification.
	 *
	 * @return the type of this notification
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this notification.
	 *
	 * @param type the type of this notification
	 */
	public void setType(String type);

	/**
	 * Returns the message of this notification.
	 *
	 * @return the message of this notification
	 */
	@AutoEscape
	public String getMessage();

	/**
	 * Sets the message of this notification.
	 *
	 * @param message the message of this notification
	 */
	public void setMessage(String message);

	/**
	 * Returns the statut of this notification.
	 *
	 * @return the statut of this notification
	 */
	@AutoEscape
	public String getStatut();

	/**
	 * Sets the statut of this notification.
	 *
	 * @param statut the statut of this notification
	 */
	public void setStatut(String statut);

	/**
	 * Returns the date creation of this notification.
	 *
	 * @return the date creation of this notification
	 */
	public Date getDateCreation();

	/**
	 * Sets the date creation of this notification.
	 *
	 * @param dateCreation the date creation of this notification
	 */
	public void setDateCreation(Date dateCreation);

	@Override
	public Notification cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}