/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package gestion_de_pharmacie.model;

import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Stock service. Represents a row in the &quot;Pharma_Stock&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>gestion_de_pharmacie.model.impl.StockModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>gestion_de_pharmacie.model.impl.StockImpl</code>.
 * </p>
 *
 * @author Farouk
 * @see Stock
 * @generated
 */
@ProviderType
public interface StockModel extends BaseModel<Stock> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a stock model instance should use the {@link Stock} interface instead.
	 */

	/**
	 * Returns the primary key of this stock.
	 *
	 * @return the primary key of this stock
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this stock.
	 *
	 * @param primaryKey the primary key of this stock
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id stock of this stock.
	 *
	 * @return the id stock of this stock
	 */
	public long getIdStock();

	/**
	 * Sets the id stock of this stock.
	 *
	 * @param idStock the id stock of this stock
	 */
	public void setIdStock(long idStock);

	/**
	 * Returns the id medicament of this stock.
	 *
	 * @return the id medicament of this stock
	 */
	public long getIdMedicament();

	/**
	 * Sets the id medicament of this stock.
	 *
	 * @param idMedicament the id medicament of this stock
	 */
	public void setIdMedicament(long idMedicament);

	/**
	 * Returns the quantite disponible of this stock.
	 *
	 * @return the quantite disponible of this stock
	 */
	public int getQuantiteDisponible();

	/**
	 * Sets the quantite disponible of this stock.
	 *
	 * @param quantiteDisponible the quantite disponible of this stock
	 */
	public void setQuantiteDisponible(int quantiteDisponible);

	/**
	 * Returns the date derniere maj of this stock.
	 *
	 * @return the date derniere maj of this stock
	 */
	public Date getDateDerniereMaj();

	/**
	 * Sets the date derniere maj of this stock.
	 *
	 * @param dateDerniereMaj the date derniere maj of this stock
	 */
	public void setDateDerniereMaj(Date dateDerniereMaj);

	@Override
	public Stock cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}