/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package gestion_de_pharmacie.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Utilisateur service. Represents a row in the &quot;Pharma_Utilisateur&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>gestion_de_pharmacie.model.impl.UtilisateurModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>gestion_de_pharmacie.model.impl.UtilisateurImpl</code>.
 * </p>
 *
 * @author Farouk
 * @see Utilisateur
 * @generated
 */
@ProviderType
public interface UtilisateurModel extends BaseModel<Utilisateur> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a utilisateur model instance should use the {@link Utilisateur} interface instead.
	 */

	/**
	 * Returns the primary key of this utilisateur.
	 *
	 * @return the primary key of this utilisateur
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this utilisateur.
	 *
	 * @param primaryKey the primary key of this utilisateur
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id utilisateur of this utilisateur.
	 *
	 * @return the id utilisateur of this utilisateur
	 */
	public long getIdUtilisateur();

	/**
	 * Sets the id utilisateur of this utilisateur.
	 *
	 * @param idUtilisateur the id utilisateur of this utilisateur
	 */
	public void setIdUtilisateur(long idUtilisateur);

	/**
	 * Returns the liferay user ID of this utilisateur.
	 *
	 * @return the liferay user ID of this utilisateur
	 */
	public long getLiferayUserId();

	/**
	 * Sets the liferay user ID of this utilisateur.
	 *
	 * @param liferayUserId the liferay user ID of this utilisateur
	 */
	public void setLiferayUserId(long liferayUserId);

	/**
	 * Returns the liferay user uuid of this utilisateur.
	 *
	 * @return the liferay user uuid of this utilisateur
	 */
	public String getLiferayUserUuid();

	/**
	 * Sets the liferay user uuid of this utilisateur.
	 *
	 * @param liferayUserUuid the liferay user uuid of this utilisateur
	 */
	public void setLiferayUserUuid(String liferayUserUuid);

	/**
	 * Returns the nom of this utilisateur.
	 *
	 * @return the nom of this utilisateur
	 */
	@AutoEscape
	public String getNom();

	/**
	 * Sets the nom of this utilisateur.
	 *
	 * @param nom the nom of this utilisateur
	 */
	public void setNom(String nom);

	/**
	 * Returns the prenom of this utilisateur.
	 *
	 * @return the prenom of this utilisateur
	 */
	@AutoEscape
	public String getPrenom();

	/**
	 * Sets the prenom of this utilisateur.
	 *
	 * @param prenom the prenom of this utilisateur
	 */
	public void setPrenom(String prenom);

	/**
	 * Returns the email of this utilisateur.
	 *
	 * @return the email of this utilisateur
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this utilisateur.
	 *
	 * @param email the email of this utilisateur
	 */
	public void setEmail(String email);

	/**
	 * Returns the mot de passe of this utilisateur.
	 *
	 * @return the mot de passe of this utilisateur
	 */
	@AutoEscape
	public String getMotDePasse();

	/**
	 * Sets the mot de passe of this utilisateur.
	 *
	 * @param motDePasse the mot de passe of this utilisateur
	 */
	public void setMotDePasse(String motDePasse);

	/**
	 * Returns the role of this utilisateur.
	 *
	 * @return the role of this utilisateur
	 */
	@AutoEscape
	public String getRole();

	/**
	 * Sets the role of this utilisateur.
	 *
	 * @param role the role of this utilisateur
	 */
	public void setRole(String role);

	/**
	 * Returns the date creation of this utilisateur.
	 *
	 * @return the date creation of this utilisateur
	 */
	public Date getDateCreation();

	/**
	 * Sets the date creation of this utilisateur.
	 *
	 * @param dateCreation the date creation of this utilisateur
	 */
	public void setDateCreation(Date dateCreation);

	@Override
	public Utilisateur cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}