/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package gestion_de_pharmacie.model;

import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the VenteDetail service. Represents a row in the &quot;Pharma_VenteDetail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>gestion_de_pharmacie.model.impl.VenteDetailModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>gestion_de_pharmacie.model.impl.VenteDetailImpl</code>.
 * </p>
 *
 * @author Farouk
 * @see VenteDetail
 * @generated
 */
@ProviderType
public interface VenteDetailModel extends BaseModel<VenteDetail> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vente detail model instance should use the {@link VenteDetail} interface instead.
	 */

	/**
	 * Returns the primary key of this vente detail.
	 *
	 * @return the primary key of this vente detail
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vente detail.
	 *
	 * @param primaryKey the primary key of this vente detail
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id detail of this vente detail.
	 *
	 * @return the id detail of this vente detail
	 */
	public long getIdDetail();

	/**
	 * Sets the id detail of this vente detail.
	 *
	 * @param idDetail the id detail of this vente detail
	 */
	public void setIdDetail(long idDetail);

	/**
	 * Returns the id vente of this vente detail.
	 *
	 * @return the id vente of this vente detail
	 */
	public long getIdVente();

	/**
	 * Sets the id vente of this vente detail.
	 *
	 * @param idVente the id vente of this vente detail
	 */
	public void setIdVente(long idVente);

	/**
	 * Returns the id medicament of this vente detail.
	 *
	 * @return the id medicament of this vente detail
	 */
	public long getIdMedicament();

	/**
	 * Sets the id medicament of this vente detail.
	 *
	 * @param idMedicament the id medicament of this vente detail
	 */
	public void setIdMedicament(long idMedicament);

	/**
	 * Returns the quantite of this vente detail.
	 *
	 * @return the quantite of this vente detail
	 */
	public int getQuantite();

	/**
	 * Sets the quantite of this vente detail.
	 *
	 * @param quantite the quantite of this vente detail
	 */
	public void setQuantite(int quantite);

	/**
	 * Returns the prix unitaire of this vente detail.
	 *
	 * @return the prix unitaire of this vente detail
	 */
	public double getPrixUnitaire();

	/**
	 * Sets the prix unitaire of this vente detail.
	 *
	 * @param prixUnitaire the prix unitaire of this vente detail
	 */
	public void setPrixUnitaire(double prixUnitaire);

	/**
	 * Returns the sous total of this vente detail.
	 *
	 * @return the sous total of this vente detail
	 */
	public double getSousTotal();

	/**
	 * Sets the sous total of this vente detail.
	 *
	 * @param sousTotal the sous total of this vente detail
	 */
	public void setSousTotal(double sousTotal);

	@Override
	public VenteDetail cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}