/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package gestion_de_pharmacie.model;

import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Vente service. Represents a row in the &quot;Pharma_Vente&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>gestion_de_pharmacie.model.impl.VenteModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>gestion_de_pharmacie.model.impl.VenteImpl</code>.
 * </p>
 *
 * @author Farouk
 * @see Vente
 * @generated
 */
@ProviderType
public interface VenteModel extends BaseModel<Vente> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vente model instance should use the {@link Vente} interface instead.
	 */

	/**
	 * Returns the primary key of this vente.
	 *
	 * @return the primary key of this vente
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vente.
	 *
	 * @param primaryKey the primary key of this vente
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id vente of this vente.
	 *
	 * @return the id vente of this vente
	 */
	public long getIdVente();

	/**
	 * Sets the id vente of this vente.
	 *
	 * @param idVente the id vente of this vente
	 */
	public void setIdVente(long idVente);

	/**
	 * Returns the id utilisateur of this vente.
	 *
	 * @return the id utilisateur of this vente
	 */
	public long getIdUtilisateur();

	/**
	 * Sets the id utilisateur of this vente.
	 *
	 * @param idUtilisateur the id utilisateur of this vente
	 */
	public void setIdUtilisateur(long idUtilisateur);

	/**
	 * Returns the date vente of this vente.
	 *
	 * @return the date vente of this vente
	 */
	public Date getDateVente();

	/**
	 * Sets the date vente of this vente.
	 *
	 * @param dateVente the date vente of this vente
	 */
	public void setDateVente(Date dateVente);

	/**
	 * Returns the montant total of this vente.
	 *
	 * @return the montant total of this vente
	 */
	public double getMontantTotal();

	/**
	 * Sets the montant total of this vente.
	 *
	 * @param montantTotal the montant total of this vente
	 */
	public void setMontantTotal(double montantTotal);

	@Override
	public Vente cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}