/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package gestion_de_pharmacie.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;

import gestion_de_pharmacie.model.Fournisseur;

import gestion_de_pharmacie.service.FournisseurService;
import gestion_de_pharmacie.service.persistence.CommandeDetailPersistence;
import gestion_de_pharmacie.service.persistence.CommandePersistence;
import gestion_de_pharmacie.service.persistence.FournisseurPersistence;
import gestion_de_pharmacie.service.persistence.MedicamentPersistence;
import gestion_de_pharmacie.service.persistence.MouvementStockPersistence;
import gestion_de_pharmacie.service.persistence.NotificationPersistence;
import gestion_de_pharmacie.service.persistence.StockPersistence;
import gestion_de_pharmacie.service.persistence.UtilisateurPersistence;
import gestion_de_pharmacie.service.persistence.VenteDetailPersistence;
import gestion_de_pharmacie.service.persistence.VentePersistence;

import java.sql.Connection;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the fournisseur remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link gestion_de_pharmacie.service.impl.FournisseurServiceImpl}.
 * </p>
 *
 * @author Farouk
 * @see gestion_de_pharmacie.service.impl.FournisseurServiceImpl
 * @generated
 */
public abstract class FournisseurServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, FournisseurService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>FournisseurService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>gestion_de_pharmacie.service.FournisseurServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			FournisseurService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		fournisseurService = (FournisseurService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return FournisseurService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Fournisseur.class;
	}

	protected String getModelClassName() {
		return Fournisseur.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = fournisseurPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected CommandePersistence commandePersistence;

	@Reference
	protected CommandeDetailPersistence commandeDetailPersistence;

	@Reference
	protected gestion_de_pharmacie.service.FournisseurLocalService
		fournisseurLocalService;

	protected FournisseurService fournisseurService;

	@Reference
	protected FournisseurPersistence fournisseurPersistence;

	@Reference
	protected MedicamentPersistence medicamentPersistence;

	@Reference
	protected MouvementStockPersistence mouvementStockPersistence;

	@Reference
	protected NotificationPersistence notificationPersistence;

	@Reference
	protected StockPersistence stockPersistence;

	@Reference
	protected UtilisateurPersistence utilisateurPersistence;

	@Reference
	protected VentePersistence ventePersistence;

	@Reference
	protected VenteDetailPersistence venteDetailPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

	private static final Log _log = LogFactoryUtil.getLog(
		FournisseurServiceBaseImpl.class);

}