/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package gestion_de_pharmacie.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;

import gestion_de_pharmacie.model.Medicament;

import gestion_de_pharmacie.service.MedicamentLocalService;
import gestion_de_pharmacie.service.persistence.CommandeDetailPersistence;
import gestion_de_pharmacie.service.persistence.CommandePersistence;
import gestion_de_pharmacie.service.persistence.FournisseurPersistence;
import gestion_de_pharmacie.service.persistence.MedicamentPersistence;
import gestion_de_pharmacie.service.persistence.MouvementStockPersistence;
import gestion_de_pharmacie.service.persistence.NotificationPersistence;
import gestion_de_pharmacie.service.persistence.StockPersistence;
import gestion_de_pharmacie.service.persistence.UtilisateurPersistence;
import gestion_de_pharmacie.service.persistence.VenteDetailPersistence;
import gestion_de_pharmacie.service.persistence.VentePersistence;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the medicament local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link gestion_de_pharmacie.service.impl.MedicamentLocalServiceImpl}.
 * </p>
 *
 * @author Farouk
 * @see gestion_de_pharmacie.service.impl.MedicamentLocalServiceImpl
 * @generated
 */
public abstract class MedicamentLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService, MedicamentLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>MedicamentLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>gestion_de_pharmacie.service.MedicamentLocalServiceUtil</code>.
	 */

	/**
	 * Adds the medicament to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect MedicamentLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param medicament the medicament
	 * @return the medicament that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Medicament addMedicament(Medicament medicament) {
		medicament.setNew(true);

		return medicamentPersistence.update(medicament);
	}

	/**
	 * Creates a new medicament with the primary key. Does not add the medicament to the database.
	 *
	 * @param idMedicament the primary key for the new medicament
	 * @return the new medicament
	 */
	@Override
	@Transactional(enabled = false)
	public Medicament createMedicament(long idMedicament) {
		return medicamentPersistence.create(idMedicament);
	}

	/**
	 * Deletes the medicament with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect MedicamentLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param idMedicament the primary key of the medicament
	 * @return the medicament that was removed
	 * @throws PortalException if a medicament with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Medicament deleteMedicament(long idMedicament)
		throws PortalException {

		return medicamentPersistence.remove(idMedicament);
	}

	/**
	 * Deletes the medicament from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect MedicamentLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param medicament the medicament
	 * @return the medicament that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Medicament deleteMedicament(Medicament medicament) {
		return medicamentPersistence.remove(medicament);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return medicamentPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			Medicament.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return medicamentPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>gestion_de_pharmacie.model.impl.MedicamentModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return medicamentPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>gestion_de_pharmacie.model.impl.MedicamentModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return medicamentPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return medicamentPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return medicamentPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public Medicament fetchMedicament(long idMedicament) {
		return medicamentPersistence.fetchByPrimaryKey(idMedicament);
	}

	/**
	 * Returns the medicament with the primary key.
	 *
	 * @param idMedicament the primary key of the medicament
	 * @return the medicament
	 * @throws PortalException if a medicament with the primary key could not be found
	 */
	@Override
	public Medicament getMedicament(long idMedicament) throws PortalException {
		return medicamentPersistence.findByPrimaryKey(idMedicament);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(medicamentLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Medicament.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("idMedicament");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			medicamentLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(Medicament.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"idMedicament");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(medicamentLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Medicament.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("idMedicament");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return medicamentPersistence.create(((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement MedicamentLocalServiceImpl#deleteMedicament(Medicament) to avoid orphaned data");
		}

		return medicamentLocalService.deleteMedicament(
			(Medicament)persistedModel);
	}

	@Override
	public BasePersistence<Medicament> getBasePersistence() {
		return medicamentPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return medicamentPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the medicaments.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>gestion_de_pharmacie.model.impl.MedicamentModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of medicaments
	 * @param end the upper bound of the range of medicaments (not inclusive)
	 * @return the range of medicaments
	 */
	@Override
	public List<Medicament> getMedicaments(int start, int end) {
		return medicamentPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of medicaments.
	 *
	 * @return the number of medicaments
	 */
	@Override
	public int getMedicamentsCount() {
		return medicamentPersistence.countAll();
	}

	/**
	 * Updates the medicament in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect MedicamentLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param medicament the medicament
	 * @return the medicament that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Medicament updateMedicament(Medicament medicament) {
		return medicamentPersistence.update(medicament);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			MedicamentLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		medicamentLocalService = (MedicamentLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return MedicamentLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Medicament.class;
	}

	protected String getModelClassName() {
		return Medicament.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = medicamentPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected CommandePersistence commandePersistence;

	@Reference
	protected CommandeDetailPersistence commandeDetailPersistence;

	@Reference
	protected FournisseurPersistence fournisseurPersistence;

	protected MedicamentLocalService medicamentLocalService;

	@Reference
	protected MedicamentPersistence medicamentPersistence;

	@Reference
	protected MouvementStockPersistence mouvementStockPersistence;

	@Reference
	protected NotificationPersistence notificationPersistence;

	@Reference
	protected StockPersistence stockPersistence;

	@Reference
	protected UtilisateurPersistence utilisateurPersistence;

	@Reference
	protected VentePersistence ventePersistence;

	@Reference
	protected VenteDetailPersistence venteDetailPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		MedicamentLocalServiceBaseImpl.class);

}